### ISSUE TITLE
2025.10.5 error message: LevoitFan' has no member named 'set_preset_mode_

### ISSUE THREAD

**Issue by adjrobinson-blip** [acvigue/esphome-levoit-air-purifier#69]
When compiling the Levoit Core 300S component on ESPHome 2025.10.5, I get the following errors:

error: 'class esphome::levoit::LevoitFan' has no member named 'set_preset_mode_'
error: 'const class esphome::fan::FanCall' has no member named 'has_preset_mode'

It seems this is caused by changes in the ESPHome fan API in recent versions. The component compiles fine on ESPHome 2023.11.x, so it appears to be a compatibility issue with newer ESPHome releases. Are you able to help?

**Comment by adjrobinson-blip** [comment]
I updated esphome and it worked fine, my mistake, apologies, thanks!
